// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGzGrhThlmtQbDgvrULarUVQvTfQuMhJI',
    appId: '1:996756086023:web:e953831a049d02d43c39a2',
    messagingSenderId: '996756086023',
    projectId: 'chat-app-2e807',
    authDomain: 'chat-app-2e807.firebaseapp.com',
    storageBucket: 'chat-app-2e807.firebasestorage.app',
    measurementId: 'G-YN4STG3E36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYjKrCJAQTgGlkU76yP8MCeTpdjq39ucU',
    appId: '1:996756086023:android:1301896d3e43d8353c39a2',
    messagingSenderId: '996756086023',
    projectId: 'chat-app-2e807',
    storageBucket: 'chat-app-2e807.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK_EhML8jjzwLYsPgxYqGfxdzL2rIqERQ',
    appId: '1:996756086023:ios:883b9528e0b127113c39a2',
    messagingSenderId: '996756086023',
    projectId: 'chat-app-2e807',
    storageBucket: 'chat-app-2e807.firebasestorage.app',
    iosBundleId: 'com.example.fireBaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK_EhML8jjzwLYsPgxYqGfxdzL2rIqERQ',
    appId: '1:996756086023:ios:883b9528e0b127113c39a2',
    messagingSenderId: '996756086023',
    projectId: 'chat-app-2e807',
    storageBucket: 'chat-app-2e807.firebasestorage.app',
    iosBundleId: 'com.example.fireBaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGzGrhThlmtQbDgvrULarUVQvTfQuMhJI',
    appId: '1:996756086023:web:9d221bf94eb1b0e03c39a2',
    messagingSenderId: '996756086023',
    projectId: 'chat-app-2e807',
    authDomain: 'chat-app-2e807.firebaseapp.com',
    storageBucket: 'chat-app-2e807.firebasestorage.app',
    measurementId: 'G-YH08F3Q9P3',
  );
}
